### ISSUE TITLE
PyAirpal debug loggers cause MemoryError even when disabled.

### ISSUE THREAD

**Issue by ebob9** [ebob9/pyairpal#1]
Running PyAirpal with large query responses causes exceptions due to debug logging statements that are not used in the rest call function:

```
RUNNING..
RUNNING..
RUNNING..
RUNNING..
FINISHED..
Process Process-2:
Traceback (most recent call last):
  File "/usr/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/usr/lib/python2.7/multiprocessing/process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
  File "./get-site-score.py", line 208, in pyairpal_worker
    output_fd.write(AirpalConnection.yield_csv(location))
  File "/home/aaron/.local/lib/python2.7/site-packages/pyairpal/__init__.py", line 160, in yield_csv
    extraheaders={'Accept': "*/*"})
  File "/home/aaron/.local/lib/python2.7/site-packages/pyairpal/__init__.py", line 303, in rest_call
    logger.debug('RESPONSE: {0}\n'.format(str(response.text)))
MemoryError
```

**Comment by ebob9** [comment]
As a follow on, should change logging to not use .format() per logger best practice, better resolution of this issue in the future is to use custom formatters. This automatically prevents logger from parsing messages it doesn't need.

https://docs.python.org/3/howto/logging-cookbook.html#use-of-alternative-formatting-styles
